services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - data:/datastore
    restart: unless-stopped
  browser-chrome:
      hostname: browser-chrome
      image: selenium/standalone-chrome-debug:3.141.59
      restart: unless-stopped
      
volumes:
  data:
    driver: local
