# Template used: https://github.com/aneisch/home-assistant-config/blob/master/extras/docker-compose/unified/docker-compose.yml
version: '3.7'
services:
  homeassistant:
    depends_on:
      - mariadb
    image: homeassistant/home-assistant:stable
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker-volumes/homeassistant-config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    ports:
      - target: 8123
        published: 8123
        mode: host
    restart: always
    networks:
      - traefik-public
  mariadb:
    image: mariadb:10.6
    user: 0:0
    environment:
      - MYSQL_ROOT_PASSWORD=!!!CENSORED!!!
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=homeassistant
      - MYSQL_USER=homeassistant
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker-volumes/homeassistant-mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
    - target: 3306
      published: 3366
      mode: host
    restart: always
networks:
  traefik-public:
    external: true
