version: '3.7'
services:
  traefik:
    image: traefik:v3
    ports:
    - target: 443
      published: 443
      mode: host
    - target: 80
      published: 80
      mode: host
    - target: 8080
      published: 81
      mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-volumes/traefik-certs:/certs:ro
      - /mnt/docker-volumes/traefik-certs/static_conf.yml:/etc/traefik/traefik.yml:ro
    restart: unless-stopped
    networks:
      - traefik-public
  whoami:
    image: traefik/whoami
    ports:
    - target: 80
      published: 8071
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.louisa.uno`)"
    restart: unless-stopped
    networks:
      - traefik-public
  renew-traefic-certs:
    image: ghcr.io/louisa-uno/renew-traefic-certs:latest
    volumes:
      - /mnt/docker-volumes/traefik-certs:/certs
    restart: unless-stopped
networks:
  traefik-public:
    external: true
