version: '3.7'
services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
    - target: 443
      published: 443
      mode: host
    - target: 80
      published: 80
      mode: host
    - target: 8080
      published: 81
      mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-volumes/traefik-certs:/certs:ro
      - /mnt/docker-volumes/traefik-certs/static_conf.yml:/etc/traefik/traefik.yml:ro
    restart: unless-stopped
    networks:
      - traefik-public
  renew-certificate:
    image: ghcr.io/louisa-uno/renew-traefic-certs:latest
    volumes:
      - /mnt/docker-volumes/traefik-certs:/certs
    restart: unless-stopped
networks:
  traefik-public:
    external: true
