version: '3.7'
services:
  dashdot:
    image: mauricenino/dashdot
    volumes:
      - /:/mnt/host:ro
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_USE_IMPERIAL=false
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_USE_NETWORK_INTERFACE=eth0
    networks:
    - cloudflared
networks:
  cloudflared:
    external: true
