version: '3.7'
services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    image: openspeedtest/latest
    networks:
    - cloudflared
networks:
  cloudflared:
    external: true
